### ISSUE TITLE
NDM pod getting restarted after deploying openebs

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#2542]
## Description
- After installing OpenEBS observed that one of the ndm pod is restarted
- ndm version v0.3.4

## Expected Behavior
- The pod is not getting restarted

## Current Behavior
- Pod is getting restarted  twice
Observed below error in previous pod logs,
```
goroutine 52 [chan receive, 17 minutes]:
runtime.gopark(0x12ebdd8, 0xc42005aa78, 0x1272b60, 0xc, 0xc420020717, 0x3)
    /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/proc.go:287 +0x12c fp=0xc4201f9690 sp=0xc4201f9660 pc=0x43c2bc
runtime.goparkunlock(0xc42005aa78, 0x1272b60, 0xc, 0x20200a2c22676e17, 0x3)
    /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/proc.go:293 +0x5e fp=0xc4201f96d0 sp=0xc4201f9690 pc=0x43c3ae
runtime.chanrecv(0xc42005aa20, 0x0, 0xc42054a501, 0xc4204d42a0)
    /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/chan.go:506 +0x304 fp=0xc4201f9780 sp=0xc4201f96d0 pc=0x4147f4
runtime.chanrecv1(0xc42005aa20, 0x0)
    /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/chan.go:388 +0x2b fp=0xc4201f97b0 sp=0xc4201f9780 pc=0x41449b
github.com/openebs/node-disk-manager/pkg/signals.SetupSignalHandler.func1(0xc42005aa20, 0xc4200725a0)
    /home/travis/gopath/src/github.com/openebs/node-disk-manager/pkg/signals/signal.go:37 +0x34 fp=0xc4201f97d0 sp=0xc4201f97b0 pc=0xf5b204
runtime.goexit()
    /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4201f97d8 sp=0xc4201f97d0 pc=0x468d41
created by github.com/openebs/node-disk-manager/pkg/signals.SetupSignalHandler
    /home/travis/gopath/src/github.com/openebs/node-disk-manager/pkg/signals/signal.go:36 +0xd0
/usr/local/bin/entrypoint.sh: line 34:     7 Aborted                 (core dumped) /usr/sbin/ndm start
```

```kubectl get nodes```
```
NAME                        STATUS   ROLES          AGE   VERSION
gitlab-master.mayalabs.io   Ready    infra,master   56d   v1.10.0+b81c8f8
gitlab-node1.mayalabs.io    Ready    compute        56d   v1.10.0+b81c8f8
gitlab-node2.mayalabs.io    Ready    compute        56d   v1.10.0+b81c8f8
gitlab-node3.mayalabs.io    Ready    compute        56d   v1.10.0+b81c8f8
gitlab-node4.mayalabs.io    Ready    compute        56d   v1.10.0+b81c8f8
gitlab-node5.mayalabs.io    Ready    compute        56d   v1.10.0+b81c8f
```
``` kubectl get pods -n openebs | grep ndm```
```
openebs-ndm-7v269                                                 1/1     Running             0          2h
openebs-ndm-8rf25                                                 1/1     Running             2          2h
openebs-ndm-j8vn8                                                 1/1     Running             0          2h
openebs-ndm-q9m5m                                                 1/1     Running             0          2h
```

ndm pod log 
[ndm.txt](https://github.com/openebs/openebs/files/3131171/ndm.txt)

**Comment by akhilerm** [comment]
Fixed in [#276](https://github.com/openebs/node-disk-manager/pull/276) in NDM repo. The crash occurred because of a memory corruption issue from seachest.
