### ISSUE TITLE
maya vsm-stats fails, when only one replica is running

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#296]
I have a volume with only one replica running. IO are happening on the volume, however the vsm-stats is erroring out with the below exception. 

```
ubuntu@kubemaster-01:~$ kubectl get pods
NAME                                                             READY     STATUS    RESTARTS   AGE
maya-apiserver-546443015-n97c8                                   1/1       Running   0          28m
openebs-provisioner-3862123968-4g5pl                             1/1       Running   0          28m
pvc-d89aea9d-9577-11e7-9029-021c6f7dbe9d-ctrl-3642784095-sxpsp   1/1       Running   0          10m
pvc-d89aea9d-9577-11e7-9029-021c6f7dbe9d-rep-511922340-6405g     0/1       Pending   0          10m
pvc-d89aea9d-9577-11e7-9029-021c6f7dbe9d-rep-511922340-d2rs6     1/1       Running   0          10m
tests-fio                                                        1/1       Running   0          10m
ubuntu@kubemaster-01:~$ 

```

```
maya vsm-stats pvc-d89aea9d-9577-11e7-902 
{
	"Iqn": "iqn.2016-09.com.openebs.jiva:pvc-d89aea9d-9577-11e7-9029-021c6f7dbe9d",
	"Volume": "pvc-d89aea9d-9577-11e7-9029-021c6f7dbe9d",
	"Portal": "10.99.8.247:3260",
	"Size": "5G"
}

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/openebs/maya/command.StatsOutput(0xc4201c2270, 0xc4201be0a0, 0xc4200103b0, 0x1, 0x1, 0xc420132f40, 0x3, 0x4, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/openebs/maya/command/vsm_stats.go:447 +0xf37
github.com/openebs/maya/command.(*VsmStatsCommand).Run(0xc4201c2270, 0xc4200103b0, 0x1, 0x1, 0xc4201c4360)
	/home/travis/gopath/src/github.com/openebs/maya/command/vsm_stats.go:187 +0x1520
github.com/openebs/maya/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4201c8000, 0xc4201c8000, 0xb, 0xc4201a0440)
	/home/travis/gopath/src/github.com/openebs/maya/vendor/github.com/mitchellh/cli/cli.go:235 +0x2d1
main.RunCustom(0xc4200103a0, 0x2, 0x2, 0xc4201b83f0, 0x0)
	/home/travis/gopath/src/github.com/openebs/maya/main.go:60 +0x490
main.Run(0xc4200103a0, 0x2, 0x2, 0xc4200001a0)
	/home/travis/gopath/src/github.com/openebs/maya/main.go:32 +0x56
main.main()
	/home/travis/gopath/src/github.com/openebs/maya/main.go:28 +0x64
```

**Comment by utkarshmani1997** [comment]
This issue is resolved in PR  c16fb5a . Close this issue
