### ISSUE TITLE
openebs-localpv-provisioner trying to delete a PV from a node that is no longer present

### ISSUE THREAD

**Issue by niladrih** [openebs/openebs#2993]
## Description

openebs-localpv-provisioner goes into crashLoopBackOff state 

```
I0409 16:59:00.010951       1 start.go:65] Starting Provisioner... 
I0409 16:59:00.033585       1 leaderelection.go:242] attempting to acquire leader lease  openebs/openebs.io-local... 
I0409 16:59:17.445316       1 leaderelection.go:252] successfully acquired lease openebs/openebs.io-local 
I0409 16:59:17.446333       1 controller.go:769] Starting provisioner controller openebs.io/local_openebs-localpv-provisioner-6f979cfcb9-xzvfp_7cf5fea3-11b1-4d5c-b2f3-f99b2a8db9ea! 
I0409 16:59:17.446402       1 event.go:281] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"openebs", Name:"openebs.io-local", UID:"177cd6da-0fc9-11ea-b0a7-0050569da282", APIVersion:"v1", ResourceVersion:"166763176", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' openebs-localpv-provisioner-6f979cfcb9-xzvfp_7cf5fea3-11b1-4d5c-b2f3-f99b2a8db9ea became leader 
I0409 16:59:17.546517       1 controller.go:818] Started provisioner controller openebs.io/local_openebs-localpv-provisioner-6f979cfcb9-xzvfp_7cf5fea3-11b1-4d5c-b2f3-f99b2a8db9ea! 
I0409 16:59:17.546706       1 controller.go:1333] delete "pvc-2371b244-202b-11ea-92cb-0050569da282": started 
2020-04-09T16:59:17.574Z	INFO	app/provisioner_hostpath.go:165	Get the Node Object from hostName: dckr-d-worker4 
E0409 16:59:17.602064       1 runtime.go:78] Observed a panic: "index out of range" (runtime error: index out of range) 
goroutine 117 [running]: 
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x161e1a0, 0x29ef2a0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3 
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82 
panic(0x161e1a0, 0x29ef2a0) 
	/home/travis/.gimme/versions/go1.12.16.linux.amd64/src/runtime/panic.go:522 +0x1b5 
github.com/openebs/maya/cmd/provisioner-localpv/app.(*Provisioner).GetNodeObjectFromHostName(0xc000374050, 0xc00005bde0, 0xe, 0x25, 0xc00056b740, 0x1) 
	/home/travis/gopath/src/github.com/openebs/maya/cmd/provisioner-localpv/app/provisioner_hostpath.go:140 +0x26e 
github.com/openebs/maya/cmd/provisioner-localpv/app.(*Provisioner).DeleteHostPath(0xc000374050, 0xc000632b50, 0x0, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/cmd/provisioner-localpv/app/provisioner_hostpath.go:168 +0x1f1 
github.com/openebs/maya/cmd/provisioner-localpv/app.(*Provisioner).Delete(0xc000374050, 0xc000632b50, 0x0, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/cmd/provisioner-localpv/app/provisioner.go:177 +0x1dc 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).deleteVolumeOperation(0xc00019c6c0, 0xc000632b50, 0x2a0d440, 0xc0004e67e0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:1348 +0x25e 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncVolume(0xc00019c6c0, 0x17e4e80, 0xc000632b50, 0x17e4e80, 0xc000632b50) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:1042 +0xb8 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncVolumeHandler(0xc00019c6c0, 0xc0000f3e00, 0x28, 0x159d680, 0xc0002c96b0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:1007 +0x186 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextVolumeWorkItem.func1(0xc00019c6c0, 0x159d680, 0xc0002c96b0, 0x0, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:932 +0xe3 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextVolumeWorkItem(0xc00019c6c0, 0xc0000d7701) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:949 +0x53 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).runVolumeWorker(0xc00019c6c0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:863 +0x2b 
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000364010) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54 
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000364010, 0x3b9aca00, 0x0, 0xc000000001, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8 
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000364010, 0x3b9aca00, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d 
created by github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).Run.func1 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:815 +0x374 
panic: runtime error: index out of range [recovered] 
	panic: runtime error: index out of range 
goroutine 117 [running]: 
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105 
panic(0x161e1a0, 0x29ef2a0) 
	/home/travis/.gimme/versions/go1.12.16.linux.amd64/src/runtime/panic.go:522 +0x1b5 
github.com/openebs/maya/cmd/provisioner-localpv/app.(*Provisioner).GetNodeObjectFromHostName(0xc000374050, 0xc00005bde0, 0xe, 0x25, 0xc00056b740, 0x1) 
	/home/travis/gopath/src/github.com/openebs/maya/cmd/provisioner-localpv/app/provisioner_hostpath.go:140 +0x26e 
github.com/openebs/maya/cmd/provisioner-localpv/app.(*Provisioner).DeleteHostPath(0xc000374050, 0xc000632b50, 0x0, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/cmd/provisioner-localpv/app/provisioner_hostpath.go:168 +0x1f1 
github.com/openebs/maya/cmd/provisioner-localpv/app.(*Provisioner).Delete(0xc000374050, 0xc000632b50, 0x0, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/cmd/provisioner-localpv/app/provisioner.go:177 +0x1dc 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).deleteVolumeOperation(0xc00019c6c0, 0xc000632b50, 0x2a0d440, 0xc0004e67e0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:1348 +0x25e 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncVolume(0xc00019c6c0, 0x17e4e80, 0xc000632b50, 0x17e4e80, 0xc000632b50) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:1042 +0xb8 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).syncVolumeHandler(0xc00019c6c0, 0xc0000f3e00, 0x28, 0x159d680, 0xc0002c96b0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:1007 +0x186 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextVolumeWorkItem.func1(0xc00019c6c0, 0x159d680, 0xc0002c96b0, 0x0, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:932 +0xe3 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).processNextVolumeWorkItem(0xc00019c6c0, 0xc0000d7701) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:949 +0x53 
github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).runVolumeWorker(0xc00019c6c0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:863 +0x2b 
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000364010) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54 
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000364010, 0x3b9aca00, 0x0, 0xc000000001, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8 
github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000364010, 0x3b9aca00, 0x0) 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d 
created by github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller.(*ProvisionController).Run.func1 
	/home/travis/gopath/src/github.com/openebs/maya/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:815 +0x374 

```
## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by kmova** [comment]
The fix to avoid the panic has been merged into 1.9.0 release. 

As a workaround till 1.9.0, the user can manually delete the PV that has been scheduled for delete using `kubectl delete pv <pv-name-shown in the logs>`. 

For the above example: `kubectl delete pv pvc-2371b244-202b-11ea-92cb-0050569da282`
