### ISSUE TITLE
openebs-ndm crashing on restart after block device resize

### ISSUE THREAD

**Issue by etherealvisage** [openebs/openebs#3362]
## Description

The NDM is crashing on startup after I gracefully brought down the cluster, resized a block device that Mayastor was using, and brought it back up again. This was discussed on the #openebs slack channel [here](https://kubernetes.slack.com/archives/CUAKPFU78/p1616114429114100).

## Expected Behavior

NDM doesn't crash :-)

## Current Behavior

NDM enters crashloop, with relevant logs:

```
I0319 00:32:13.962636       8 udevprobe.go:334] starting udev probe listener

I0319 00:32:13.965432       8 udevprobe.go:203] device: /dev/vda, PartitionTableUUID: 38b063e4 filled during udev scan

I0319 00:32:13.965625       8 udevprobe.go:228] Dependents of /dev/vda : {Parent: Partitions:[/dev/vda1 /dev/vda2 /dev/vda3] Holders:[] Slaves:[]}

I0319 00:32:13.965639       8 udevprobe.go:238] Device: /dev/vda is of type: disk

I0319 00:32:13.965739       8 udevprobe.go:203] device: /dev/vda1, PartitionTableUUID: 38b063e4 filled during udev scan

I0319 00:32:13.965746       8 udevprobe.go:207] device: /dev/vda1, PartitionEntryUUID: 38b063e4-01 filled during udev scan

I0319 00:32:13.965749       8 udevprobe.go:211] device: /dev/vda1, FileSystemUUID: c7499a60-1700-47e6-8808-54cc6e4bb49d filled during udev scan

I0319 00:32:13.965882       8 udevprobe.go:228] Dependents of /dev/vda1 : {Parent:/dev/vda Partitions:[] Holders:[] Slaves:[]}

I0319 00:32:13.965911       8 udevprobe.go:238] Device: /dev/vda1 is of type: partition

I0319 00:32:13.966013       8 udevprobe.go:203] device: /dev/vda2, PartitionTableUUID: 38b063e4 filled during udev scan

I0319 00:32:13.966020       8 udevprobe.go:207] device: /dev/vda2, PartitionEntryUUID: 38b063e4-02 filled during udev scan

I0319 00:32:13.966115       8 udevprobe.go:228] Dependents of /dev/vda2 : {Parent:/dev/vda Partitions:[] Holders:[] Slaves:[]}

I0319 00:32:13.966122       8 udevprobe.go:238] Device: /dev/vda2 is of type: partition

I0319 00:32:13.966286       8 udevprobe.go:203] device: /dev/vda3, PartitionTableUUID: 38b063e4 filled during udev scan

I0319 00:32:13.966294       8 udevprobe.go:207] device: /dev/vda3, PartitionEntryUUID: 38b063e4-03 filled during udev scan

I0319 00:32:13.966297       8 udevprobe.go:211] device: /dev/vda3, FileSystemUUID: d5dada6b-358d-40c8-8c00-d16e2614d9b9 filled during udev scan

I0319 00:32:13.966480       8 udevprobe.go:228] Dependents of /dev/vda3 : {Parent:/dev/vda Partitions:[] Holders:[] Slaves:[]}

I0319 00:32:13.966508       8 udevprobe.go:238] Device: /dev/vda3 is of type: partition

I0319 00:32:13.966707       8 udevprobe.go:199] device: /dev/sr0, Serial: QM00001 filled during udev scan

I0319 00:32:13.966846       8 udevprobe.go:228] Dependents of /dev/sr0 : {Parent: Partitions:[] Holders:[] Slaves:[]}

I0319 00:32:13.966853       8 udevprobe.go:238] Device: /dev/sr0 is of type: disk

I0319 00:32:13.967117       8 udevprobe.go:228] Dependents of  : {Parent: Partitions:[/dev/bin /dev/boot /dev/dev /dev/etc /dev/home /dev/host /dev/lib /dev/lib32 /dev/lib64 /dev/libx32 /dev/media /dev/mnt /dev/opt /dev/proc /dev/root /dev/run /dev/sbin /dev/srv /dev/sys /dev/tmp /dev/usr /dev/var] Holders:[] Slaves:[]}

panic: runtime error: slice bounds out of range [:3] with length 0

goroutine 1 [running]:

panic(0x167d980, 0xc0005f88a0)

    /usr/local/go/src/runtime/panic.go:1064 +0x46d fp=0xc0001516a8 sp=0xc0001515f0 pc=0x444f2d

runtime.goPanicSliceAlen(0x3, 0x0)

    /usr/local/go/src/runtime/panic.go:98 +0xa3 fp=0xc0001516f0 sp=0xc0001516a8 pc=0x442ee3

github.com/openebs/node-disk-manager/pkg/sysfs.isDM(...)

    /go/src/github.com/openebs/node-disk-manager/pkg/sysfs/syspath.go:320

github.com/openebs/node-disk-manager/pkg/sysfs.Device.GetDeviceType(0x0, 0x0, 0x0, 0x0, 0xc000046bb0, 0x2, 0xc000046b6c, 0x4, 0xc000156600, 0x16, ...)

    /go/src/github.com/openebs/node-disk-manager/pkg/sysfs/syspath.go:282 +0x45c fp=0xc000151758 sp=0xc0001516f0 pc=0x1293f0c

github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe.(*udevProbe).scan(0xc000584c40, 0x0, 0x0)

    /go/src/github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe/udevprobe.go:232 +0xbfd fp=0xc000151b58 sp=0xc000151758 pc=0x13add4d

github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe.(*udevProbe).Start(0xc000584c00)

    /go/src/github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe/udevprobe.go:123 +0x76 fp=0xc000151b80 sp=0xc000151b58 pc=0x13acfc6

github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe.(*registerProbe).register(0xc000151c60)

    /go/src/github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe/probe.go:59 +0xb3 fp=0xc000151ba0 sp=0xc000151b80 pc=0x13a9e63

github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe.glob..func5()

    /go/src/github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe/udevprobe.go:67 +0x1b1 fp=0xc000151ca8 sp=0xc000151ba0 pc=0x13b2571

github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe.Start(0x2534a80, 0x7, 0x7)

    /go/src/github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe/probe.go:67 +0x96 fp=0xc000151d00 sp=0xc000151ca8 pc=0x13a9f36

github.com/openebs/node-disk-manager/cmd/ndm_daemonset/app/command.NewCmdStart.func1(0xc00042ab00, 0xc000584000, 0x0, 0x2)

    /go/src/github.com/openebs/node-disk-manager/cmd/ndm_daemonset/app/command/start.go:65 +0x1d6 fp=0xc000151d78 sp=0xc000151d00 pc=0x13ca266

github.com/spf13/cobra.(*Command).execute(0xc00042ab00, 0xc0003357e0, 0x2, 0x2, 0xc00042ab00, 0xc0003357e0)

    /go/src/github.com/openebs/node-disk-manager/vendor/github.com/spf13/cobra/command.go:842 +0x29d fp=0xc000151e50 sp=0xc000151d78 pc=0x12ad20d

github.com/spf13/cobra.(*Command).ExecuteC(0xc00042a2c0, 0x0, 0x0, 0x41759f)

    /go/src/github.com/openebs/node-disk-manager/vendor/github.com/spf13/cobra/command.go:943 +0x317 fp=0xc000151f28 sp=0xc000151e50 pc=0x12adeb7

github.com/spf13/cobra.(*Command).Execute(...)

    /go/src/github.com/openebs/node-disk-manager/vendor/github.com/spf13/cobra/command.go:883

main.run(0x0, 0x0)

    /go/src/github.com/openebs/node-disk-manager/cmd/ndm_daemonset/main.go:49 +0x94 fp=0xc000151f68 sp=0xc000151f28 pc=0x13ca7b4

main.main()

    /go/src/github.com/openebs/node-disk-manager/cmd/ndm_daemonset/main.go:28 +0x22 fp=0xc000151f88 sp=0xc000151f68 pc=0x13ca6e2

runtime.main()

    /usr/local/go/src/runtime/proc.go:203 +0x1fa fp=0xc000151fe0 sp=0xc000151f88 pc=0x44797a

runtime.goexit()

    /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000151fe8 sp=0xc000151fe0 pc=0x475171

<snip other goroutines>
```

## Steps to Reproduce

Not sure, I haven't been able to reproduce it on other clusters yet. Relevant actions that I performed around the time this started were bringing the node down, resizing a block device, and restarting the VM that the node is running on.

## Your Environment

* `kubectl get nodes`:
```
NAME          STATUS   ROLES                  AGE   VERSION
k8s-staging   Ready    control-plane,master   28d   v1.20.4
```
* `kubectl get sc`:
```
NAME                        PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ms                          io.openebs.csi-mayastor                                    Delete          Immediate              false                  28d
openebs-device              openebs.io/local                                           Delete          WaitForFirstConsumer   false                  28d
openebs-hostpath            openebs.io/local                                           Delete          WaitForFirstConsumer   false                  28d
openebs-jiva-default        openebs.io/provisioner-iscsi                               Delete          Immediate              false                  28d
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  28d
```
* `kubectl get pv`:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                            STORAGECLASS   REASON   AGE
pvc-01ae4d3b-e2ea-43f6-a61d-2e1fdeae7d84   10Gi       RWO            Delete           Bound    registry/registry-images                         ms                      15d
pvc-2b4c9d27-72be-4eec-87de-66c2c004b2de   50Mi       RWO            Delete           Bound    <snip>   ms                      6d22h
pvc-36415533-0192-4407-8df9-f1f548bfa272   5Gi        RWO            Delete           Bound    <snip>                      6d22h
pvc-37c3e3fb-d734-4f0c-b6cc-f62d349d40b3   50Mi       RWO            Delete           Bound    <snip>   ms                      8d
pvc-525d62fa-7fd7-468e-9074-4823a0f415b9   5Gi        RWO            Delete           Bound    <snip>                      13d
pvc-58f643e4-7109-483b-873c-7419fa8ee3c6   256Mi      RWO            Delete           Bound    <snip>         ms                      13d
pvc-5e80762e-f8b9-4913-a005-1de02ab70c10   5Gi        RWO            Delete           Bound    <snip>                      13d
pvc-60aa79da-a19b-41fd-b0ac-cf5918969b18   5Gi        RWO            Delete           Bound    <snip>         ms                      13d
pvc-61de04da-5dd2-45d0-aaa7-e56505bf61dd   5Gi        RWO            Delete           Bound    <snip>         ms                      6d22h
pvc-7693ec85-7974-416a-8960-b8dcbe569e29   50Mi       RWO            Delete           Bound    <snip>   ms                      11d
pvc-7c7267ef-c805-403d-9585-bb56416503a1   5Gi        RWO            Delete           Bound    <snip>              ms                      8d
pvc-9460c1f0-9fb9-4646-9be3-a73ffd1b1198   5Gi        RWO            Delete           Bound    <snip>                   ms                      8d
pvc-b013942d-b902-4b36-96b2-cf143543037c   256Mi      RWO            Delete           Bound    <snip>         ms                      8d
pvc-b3d639a5-7b0a-483c-a0b9-9ff74700f1a0   5Gi        RWO            Delete           Bound    <snip>         ms                      8d
pvc-de91b709-88cf-4801-a94f-25bf1f721f64   256Mi      RWO            Delete           Bound    <snip>         ms                      6d22h
pvc-f47a7b36-231f-46d2-9667-b5c6a9962705   5Gi        RWO            Delete           Bound    <snip>              ms                      6d22h

```
* OS (from `/etc/os-release`): `PRETTY_NAME="Debian GNU/Linux 10 (buster)"`
* Kernel (from `uname -a`):
```Linux k8s-staging 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux```
* Install tools: kubeadm
* Others:

```
$ lsblk
NAME     MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0       11:0    1 1024M  0 rom  
vda      254:0    0  200G  0 disk 
├─vda1   254:1    0   14G  0 part /
├─vda2   254:2    0  150G  0 part 
└─vda3   254:3    0   36G  0 part /var/lib/containerd
nvme0n1  259:1    0    5G  0 disk /var/lib/kubelet/pods/f8c5d4c9-b4cc-499b-bb84-73ec21c67ce8/volumes/kubernetes.io~csi/pvc-36415533-0192-4407-8df9-f1f548bfa272/mount
nvme1n1  259:3    0    5G  0 disk /var/lib/kubelet/pods/d6d54604-bae8-4638-9c4a-e2cddd79f2f3/volumes/kubernetes.io~csi/pvc-b3d639a5-7b0a-483c-a0b9-9ff74700f1a0/mount
<snip more mayastor nvme devices>
```

**Comment by akhilerm** [comment]
Sorry for the late reply @etherealvisage . I have raised a [fix](https://github.com/openebs/node-disk-manager/pull/560) for it.
The crash is happening because an empty devicename is getting detected, need to see why it happens.

For further debugging:
1.  can you share the complete logs of the NDM pod.  
2. `fdisk -l`
3. `udevadm info <nvme-disks>`

Also, are you using NDM and mayastor together?
