### ISSUE TITLE
Failed to upgrade cStor SPC from 2.1.0 to 2.8.0

### ISSUE THREAD

**Issue by sgielen** [openebs/openebs#3392]
## Description
I just performed an upgrade from OpenEBS 2.1.0 to 2.8.0. It mostly went by without a hiccup, but eventually, upgrading the SPC failed with the following error:

```
I0515 11:03:27.061638       1 cstor_spc.go:100] Started upgrading storagePoolClaim{cstor-disk-pool} from 2.1.0 to 2.8.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0xd5acf8]

goroutine 1 [running]:
github.com/openebs/maya/pkg/upgrade/upgrader.updateUpgradeDetailedStatus(0x0, 0x1034d43, 0xb, 0xc02008885a866fd4, 0x80525c3d0, 0x1ced5c0, 0xc02008885a866fd4, 0x80525c3d0, 0x1ced5c0, 0x1031c95, ...)
	/go/src/github.com/openebs/maya/pkg/upgrade/upgrader/helper.go:213 +0x1d8
github.com/openebs/maya/pkg/upgrade/upgrader.spcUpgrade(0x7fcd357068, 0xf, 0x4000046032, 0x7, 0x1cedaa0, 0x40004cf180, 0x0)
	/go/src/github.com/openebs/maya/pkg/upgrade/upgrader/spc_upgrade.go:76 +0x24c
github.com/openebs/maya/pkg/upgrade/upgrader.Exec(0x7fcd35702c, 0x5, 0x7fcd35703f, 0x5, 0x103a10f, 0x10, 0x7fcd357068, 0xf, 0x4000046032, 0x7, ...)
	/go/src/github.com/openebs/maya/pkg/upgrade/upgrader/exec.go:115 +0x868
github.com/openebs/maya/cmd/upgrade/executor.(*UpgradeOptions).RunCStorSPCUpgrade(0x1cdb3c0, 0x4000455900, 0x10e0420, 0x0)
	/go/src/github.com/openebs/maya/cmd/upgrade/executor/cstor_spc.go:107 +0x204
github.com/openebs/maya/cmd/upgrade/executor.singleCStorSPCUpgrade(0x4000455900)
	/go/src/github.com/openebs/maya/cmd/upgrade/executor/cstor_spc.go:78 +0xd8
github.com/openebs/maya/cmd/upgrade/executor.bulkCStorSPCUpgrade(0x4000455900, 0x400047b5e0, 0x1, 0x5)
	/go/src/github.com/openebs/maya/cmd/upgrade/executor/cstor_spc.go:84 +0x88
github.com/openebs/maya/cmd/upgrade/executor.NewUpgradeCStorSPCJob.func1(0x4000455900, 0x400047b5e0, 0x1, 0x5)
	/go/src/github.com/openebs/maya/cmd/upgrade/executor/cstor_spc.go:62 +0xe0
github.com/spf13/cobra.(*Command).execute(0x4000455900, 0x400047b590, 0x5, 0x5, 0x4000455900, 0x400047b590)
	/go/src/github.com/openebs/maya/vendor/github.com/spf13/cobra/command.go:830 +0x1c4
github.com/spf13/cobra.(*Command).ExecuteC(0x4000455400, 0x0, 0x400005c768, 0x43754)
	/go/src/github.com/openebs/maya/vendor/github.com/spf13/cobra/command.go:914 +0x22c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/openebs/maya/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/go/src/github.com/openebs/maya/cmd/upgrade/main.go:29 +0x44
```

I have only a single spc in the cluster called `cstor-disk-pool`, this is its YAML:

```
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 200Mi
            ephemeral-storage: "100Mi"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"openebs.io/v1alpha1","kind":"StoragePoolClaim","metadata":{"annotations":{"cas.openebs.io/config":"- name: PoolResourceRequests\n  value: |-\n      memory: 200Mi\n      ephemeral-storage: \"100Mi\"\n"},"name":"cstor-disk-pool"},"spec":{"blockDevices":{"blockDeviceList":["blockdevice-e728c07ebb509b1ab5881e975f8189a2","blockdevice-1e6340d5fd05cb2cd1b3e725efbbc5be","blockdevice-dc383288a2a1a4816b4dac791d01e768"]},"name":"cstor-disk-pool","poolSpec":{"poolType":"striped"},"type":"disk"}}
    openebs.io/spc-lease: '{"holder":"","leaderTransition":6}'
  creationTimestamp: "2020-04-25T15:20:28Z"
  finalizers:
  - storagepoolclaim.openebs.io/finalizer
  generation: 19
  name: cstor-disk-pool
  resourceVersion: "99949818"
  selfLink: /apis/openebs.io/v1alpha1/storagepoolclaims/cstor-disk-pool
  uid: 659026c6-2aa0-4c96-be90-bc115680bf4e
spec:
  blockDevices:
    blockDeviceList:
    - blockdevice-3ce583a5ae11343272b9ae2a044798a0
    - blockdevice-5d9e02b3865c779a7d56804454126406
    - blockdevice-b86b3018f7ae807a1d336665f0af2685
  maxPools: null
  minPools: 0
  name: cstor-disk-pool
  poolSpec:
    cacheFile: ""
    overProvisioning: false
    poolType: striped
    roThresholdLimit: 0
    thickProvisioning: false
  type: disk
status:
  phase: Online
versionDetails:
  autoUpgrade: false
  desired: 2.1.0
  status:
    current: 2.1.0
    dependentsUpgraded: true
    lastUpdateTime: "2020-10-04T12:08:03Z"
    state: Reconciled
```

At this point;
- all control plane Pods were running 2.8.0
- 2 out of 3 cStor disk pool pods were running and one was still ContainerCreating (all 2.8.0)
- all PVC targets were still running 2.1.0
- all volumes were healthy, except one: 1/3 Rebuilding, 1/3 Degraded, 1/3 showed as Healthy but the cStor disk pool behind it was still ContainerCreating

## Your Environment
* `kubectl get nodes`: 3 Raspberry Pi arm64 nodes
* OS (from `/etc/os-release`): k3os
* Kernel (from `uname -a`): `Linux kristel 4.19.75-v8+ #1270 SMP PREEMPT Tue Sep 24 18:59:17 BST 2019 aarch64 GNU/Linux`

**Comment by sgielen** [comment]
Apparently, panic is occurring on this line:
https://github.com/openebs/maya/blob/v2.8.0/pkg/upgrade/upgrader/helper.go#L213

If I look at the parameters correctly, first parameter `uTask` is `0x0` causing null ptr dereference. 

Value is coming from here: https://github.com/openebs/maya/blob/v2.8.0/pkg/upgrade/upgrader/spc_upgrade.go#L68-L76

**Comment by shubham14bajpai** [comment]
An easy way to fix this would be to delete all the `utasks` in openebs namespace. The job will create a new one when it is launched again. The log was disabled as this is an experimental way of upgrading all the components automatically and provide status via external controllers which we are working on.

**Comment by sgielen** [comment]
Gotcha! The upgrade tasks did not contain an entry for this upgrade yet. However, I restarted the job **after** the last cStor disk pool was fully Running (no longer ContainerCreating) and now the log says:

```
I0515 12:13:47.786292       1 cstor_spc.go:100] Started upgrading storagePoolClaim{cstor-disk-pool} from 2.1.0 to 2.8.0
I0515 12:13:48.306299       1 csp_upgrade.go:193] csp deployment cstor-disk-pool-7it6 already in 2.8.0 version
I0515 12:13:48.307009       1 csp_upgrade.go:155] csp cstor-disk-pool-7it6 already in 2.8.0 version
I0515 12:13:48.324890       1 csp_upgrade.go:380] Upgrade Successful for csp cstor-disk-pool-7it6
I0515 12:13:49.721927       1 csp_upgrade.go:193] csp deployment cstor-disk-pool-una0 already in 2.8.0 version
I0515 12:13:49.722012       1 csp_upgrade.go:155] csp cstor-disk-pool-una0 already in 2.8.0 version
I0515 12:13:49.923693       1 csp_upgrade.go:380] Upgrade Successful for csp cstor-disk-pool-una0
I0515 12:13:51.723206       1 csp_upgrade.go:193] csp deployment cstor-disk-pool-eiq0 already in 2.8.0 version
I0515 12:13:51.750217       1 csp_upgrade.go:153] patched csp cstor-disk-pool-eiq0
I0515 12:13:51.750336       1 csp_upgrade.go:277] Verifying the reconciliation of version for cstor-disk-pool-eiq0 { phase:Healthy }
I0515 12:14:01.765769       1 csp_upgrade.go:277] Verifying the reconciliation of version for cstor-disk-pool-eiq0 { phase:Healthy }
I0515 12:14:11.800886       1 csp_upgrade.go:380] Upgrade Successful for csp cstor-disk-pool-eiq0
I0515 12:14:11.890884       1 spc_upgrade.go:148] Verifying the reconciliation of version for cstor-disk-pool
I0515 12:14:21.909991       1 spc_upgrade.go:102] Upgrade Successful for spc cstor-disk-pool
I0515 12:14:21.910088       1 cstor_spc.go:120] Successfully upgraded storagePoolClaim{cstor-disk-pool} from 2.1.0 to 2.8.0
```

**Comment by sgielen** [comment]
I think the error occurred because `cstor-disk-pool-eiq0` took too long to start again. Remember that this is running on a couple of Raspberry Pi 4's, so pulling the three large cstor-disk-pool images and starting the container can take ~30 minutes.

**Comment by shubham14bajpai** [comment]
Nice the job is meant to correct itself on restarts. Still the nil pointer errors should not happen. I will try to reproduce and handle those in the code.

**Comment by sgielen** [comment]
> Nice the job is meant to correct itself on restarts. Still the nil pointer errors should not happen. I will try to reproduce and handle those in the code.

It did, but it failed four times in pretty rapid succession so the Job had given up before the cStor pool was fully healthy again.

**Comment by sgielen** [comment]
Interestingly, even now the `upgradetasks` in the cluster don't contain any information on the `2.8.0` upgrade. Is that what you meant with the log being disabled?

**Comment by shubham14bajpai** [comment]
Can you paste the -oyaml of any one of the CR
