### ISSUE TITLE
Unable to remove failed cStor pool from cspc with runtime error in cstor-admission-server

### ISSUE THREAD

**Issue by jpflouret** [openebs/openebs#3629]
## Description
I had a node failure and I manually deleted the cspi for the failed pool before removing the pool from the cstor pool cluster spec. Now I'm unable to remove the failed pool from the cspc. When I edit the spec and remove the pool I get the following error:

```
$ kubectl -n openebs edit cspc cstor-pool-cluster
error: cstorpoolclusters.cstor.openebs.io "cstor-pool-cluster" could not be patched: Internal error occurred: failed calling webhook "admission-webhook.cstor.openebs.io": failed to call webhook: Post "https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s": EOF
```

Logs for the admission server show the runtime error in ValidateScaledown in cscp.go 
```
$ kubectl -n openebs logs openebs-cstor-admission-server-5f776fdfcc-4sbxz 
...
2023/04/24 04:38:37 http: panic serving 10.244.5.0:23642: runtime error: index out of range [0] with length 0
goroutine 39 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x1619340, 0xc0000af740})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/openebs/cstor-operators/pkg/webhook.(*PoolOperations).ValidateScaledown(0xc0005076c0)
	/go/src/github.com/openebs/cstor-operator/pkg/webhook/cspc.go:581 +0xb56
github.com/openebs/cstor-operators/pkg/webhook.(*webhook).validateCSPCUpdateRequest(0xc0003674d0, 0xc0002f8ea0, 0x17cd490)
	/go/src/github.com/openebs/cstor-operator/pkg/webhook/cspc.go:518 +0x533
github.com/openebs/cstor-operators/pkg/webhook.(*webhook).validateCSPC(0xc000489190?, 0x10?)
	/go/src/github.com/openebs/cstor-operator/pkg/webhook/cspc.go:121 +0x108
github.com/openebs/cstor-operators/pkg/webhook.(*webhook).validate(0xc00009ab70?, 0xc00009ac30)
	/go/src/github.com/openebs/cstor-operator/pkg/webhook/webhook.go:200 +0x22a
github.com/openebs/cstor-operators/pkg/webhook.(*webhook).Serve(0x11bfa0?, {0x191c9e8, 0xc000194460}, 0xc000182a00)
	/go/src/github.com/openebs/cstor-operator/pkg/webhook/webhook.go:244 +0x352
net/http.HandlerFunc.ServeHTTP(0xc000194460?, {0x191c9e8?, 0xc000194460?}, 0x16fd004?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0001383ff?, {0x191c9e8, 0xc000194460}, 0xc000182a00)
	/usr/local/go/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0x1910dd8?}, {0x191c9e8, 0xc000194460}, 0xc000182a00)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0003feb40, {0x191d300, 0xc0003c6780})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db
...
```

Error occurs here:
https://github.com/openebs/cstor-operators/blob/25db0f4b41be4f4eb3c13e16e3a456e6439b94b4/pkg/webhook/cspc.go#L581

I found [this guide](https://github.com/openebs/cstor-operators/blob/develop/docs/troubleshooting/migrate_cstor_volume.md#step3-remove-the-pool-spec-from-cspc-belongs-to-lost-node) with instructions similar to what I was doing except I manually deleted the cspi which seems to be the problem in the code above.

I need to remove this pool instance from my cluster and I'm stuck on what to do next. Any help would be appreciated.

Thanks in advance.

## Expected Behavior

I am able to remove pool from cspc.

## Current Behavior

Runtime error in cstor-admission-server prevents edit of cspc.

## Possible Solution

Code should check if index 0 is valid before attempting to access `cspi.Items[0]`

## Steps to Reproduce

Manually deleted cspi for failed node before attempting to edit cscp.

## Screenshots

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/9397098/233908333-141befd9-1f38-4a87-b5ce-8a5156586dfe.png">

## Your Environment
* `kubectl get nodes`:
```
NAME              STATUS   ROLES           AGE     VERSION
k8s-master-1      Ready    control-plane   5h12m   v1.27.1
k8s-master-2      Ready    control-plane   3h15m   v1.27.1
k8s-pi-master-1   Ready    control-plane   32h     v1.27.1
k8s-worker-1      Ready    worker          5d13h   v1.27.1
k8s-worker-2      Ready    worker          5d12h   v1.27.1
k8s-worker-3      Ready    worker          57m     v1.27.1
```
* `kubectl get pods --all-namespaces`:
```
NAMESPACE              NAME                                                              READY   STATUS      RESTARTS         AGE
cert-manager           cert-manager-654df755c5-nfgkm                                     1/1     Running     14 (3h43m ago)   5d13h
cert-manager           cert-manager-cainjector-55c69fbf8-q5h6v                           1/1     Running     16 (3h47m ago)   5d13h
cert-manager           cert-manager-webhook-65ddf78f48-7jzd9                             1/1     Running     1 (24h ago)      5d13h
external-dns           external-dns-85cc6b49d7-pdnrw                                     1/1     Running     1 (24h ago)      5d13h
external-ingress       external-ingress-controller-55cfb4dd84-b7k46                      1/1     Running     1 (24h ago)      5d13h
gitlab-runner          gitlab-runner-849b48db7d-n445k                                    1/1     Running     1 (24h ago)      5d13h
grafana                grafana-7c6885cdd9-kntzh                                          1/1     Running     12 (24h ago)     3d2h
grafana                grafana-image-renderer-7ffc5f57d8-dxb82                           1/1     Running     1 (24h ago)      3d2h
ingress-nginx          ingress-nginx-controller-7856f5d9f9-pd9jv                         1/1     Running     1 (24h ago)      5d13h
kube-flannel           kube-flannel-ds-68kbl                                             1/1     Running     1 (24h ago)      5d13h
kube-flannel           kube-flannel-ds-7vt2j                                             1/1     Running     1 (3h47m ago)    5h12m
kube-flannel           kube-flannel-ds-l9cpx                                             1/1     Running     4 (24h ago)      6d20h
kube-flannel           kube-flannel-ds-qzvbv                                             1/1     Running     1 (3h44m ago)    32h
kube-flannel           kube-flannel-ds-xws4w                                             1/1     Running     0                3h16m
kube-flannel           kube-flannel-ds-zd7qs                                             1/1     Running     0                57m
kube-system            coredns-5d78c9869d-jz7d6                                          1/1     Running     1 (3h47m ago)    4h20m
kube-system            coredns-5d78c9869d-qqxmb                                          1/1     Running     0                144m
kube-system            descheduler-28038572-tgqgs                                        0/1     Completed   0                4m31s
kube-system            descheduler-28038574-2tnlx                                        0/1     Completed   0                2m31s
kube-system            descheduler-28038576-ft44c                                        0/1     Completed   0                31s
kube-system            etcd-k8s-master-1                                                 1/1     Running     1 (3h47m ago)    5h12m
kube-system            etcd-k8s-master-2                                                 1/1     Running     0                3h16m
kube-system            etcd-k8s-pi-master-1                                              1/1     Running     1 (3h44m ago)    32h
kube-system            kube-apiserver-k8s-master-1                                       1/1     Running     2 (3h43m ago)    5h12m
kube-system            kube-apiserver-k8s-master-2                                       1/1     Running     0                3h16m
kube-system            kube-apiserver-k8s-pi-master-1                                    1/1     Running     3 (3h44m ago)    32h
kube-system            kube-controller-manager-k8s-master-1                              1/1     Running     2 (3h44m ago)    5h12m
kube-system            kube-controller-manager-k8s-master-2                              1/1     Running     0                3h16m
kube-system            kube-controller-manager-k8s-pi-master-1                           1/1     Running     3 (3h44m ago)    32h
kube-system            kube-proxy-2654s                                                  1/1     Running     1 (3h44m ago)    32h
kube-system            kube-proxy-bv5cc                                                  1/1     Running     4 (24h ago)      6d20h
kube-system            kube-proxy-ggmsv                                                  1/1     Running     0                3h16m
kube-system            kube-proxy-gmmdr                                                  1/1     Running     1 (3h47m ago)    5h12m
kube-system            kube-proxy-lnbhk                                                  1/1     Running     1 (24h ago)      5d13h
kube-system            kube-proxy-zrkfp                                                  1/1     Running     0                57m
kube-system            kube-scheduler-k8s-master-1                                       1/1     Running     2 (3h44m ago)    5h12m
kube-system            kube-scheduler-k8s-master-2                                       1/1     Running     0                3h16m
kube-system            kube-scheduler-k8s-pi-master-1                                    1/1     Running     3 (3h44m ago)    32h
kubernetes-dashboard   dashboard-metrics-scraper-5cb4f4bb9c-kkn9w                        1/1     Running     1 (24h ago)      5d13h
kubernetes-dashboard   kubernetes-dashboard-6967859bff-wbm8x                             1/1     Running     9 (3h46m ago)    5d13h
metallb-system         metallb-controller-7d644d8b89-8hs8m                               1/1     Running     1 (24h ago)      5d13h
metallb-system         metallb-speaker-5hnv4                                             1/1     Running     2 (3h45m ago)    5h12m
metallb-system         metallb-speaker-8b2j4                                             1/1     Running     0                57m
metallb-system         metallb-speaker-mvrxz                                             1/1     Running     2 (24h ago)      5d13h
metallb-system         metallb-speaker-qvvbm                                             1/1     Running     2 (3h42m ago)    32h
metallb-system         metallb-speaker-r2h4d                                             1/1     Running     9 (24h ago)      6d14h
metallb-system         metallb-speaker-w8sdm                                             1/1     Running     0                3h16m
openebs                cstor-disk-pool-64s6-7dcccfd7bb-9cb2z                             3/3     Running     3 (24h ago)      5d1h
openebs                cstor-disk-pool-nrq2-7c8c67d47c-4t75t                             3/3     Running     0                24h
openebs                openebs-cstor-admission-server-5f776fdfcc-4sbxz                   1/1     Running     0                73m
openebs                openebs-cstor-csi-controller-0                                    6/6     Running     0                144m
openebs                openebs-cstor-csi-node-9gxxk                                      2/2     Running     2 (24h ago)      5d6h
openebs                openebs-cstor-csi-node-j46vk                                      2/2     Running     0                57m
openebs                openebs-cstor-csi-node-rz5b5                                      2/2     Running     8 (24h ago)      5d6h
openebs                openebs-cstor-cspc-operator-7dddff5986-tkpck                      1/1     Running     0                144m
openebs                openebs-cstor-cvc-operator-b8f9d8dcf-xzlk2                        1/1     Running     0                144m
openebs                openebs-localpv-provisioner-7c8ffb99f9-cvftk                      1/1     Running     0                144m
openebs                openebs-ndm-hnzdv                                                 1/1     Running     2 (24h ago)      5d6h
openebs                openebs-ndm-operator-56c5b679f7-m7bnq                             1/1     Running     0                144m
openebs                openebs-ndm-pnxdz                                                 1/1     Running     8 (24h ago)      5d6h
openebs                openebs-ndm-w65c7                                                 1/1     Running     0                57m
openebs                pvc-6bc3952d-5d34-45b8-94e3-50df769a96dc-target-6667cf6957fttdg   3/3     Running     0                24h
openebs                pvc-a3f50650-1d1d-4d2f-9062-49eea74f3c4b-target-8bbd745b9-xcsmc   3/3     Running     0                24h
openebs                pvc-b73af6dc-11f9-407f-8a49-b479869efcc0-target-7c654b668bx4wmt   3/3     Running     0                24h
openebs                pvc-bb0dc064-ce53-48e3-8788-7a5a7aae9655-target-5f5c78fb5bgngnd   3/3     Running     0                24h
portainer              portainer-7ffd7d64c9-9bzw8                                        1/1     Running     0                144m
prometheus             prometheus-alertmanager-0                                         1/1     Running     1 (24h ago)      3d5h
prometheus             prometheus-blackbox-exporter-545d775d85-brqt8                     1/1     Running     0                144m
prometheus             prometheus-kube-state-metrics-64b4cd6658-t668p                    1/1     Running     0                144m
prometheus             prometheus-nut-exporter-765b8d6d8f-bnpxr                          1/1     Running     0                144m
prometheus             prometheus-pihole-exporter-7c9d9b5c65-sg9q8                       1/1     Running     2 (24h ago)      4d20h
prometheus             prometheus-prometheus-node-exporter-gd8rz                         1/1     Running     1 (3h44m ago)    32h
prometheus             prometheus-prometheus-node-exporter-q2xfz                         1/1     Running     0                57m
prometheus             prometheus-prometheus-node-exporter-rhgbm                         1/1     Running     1 (24h ago)      3d5h
prometheus             prometheus-prometheus-node-exporter-s9sph                         1/1     Running     2 (24h ago)      3d5h
prometheus             prometheus-prometheus-node-exporter-zhlvj                         1/1     Running     1 (3h47m ago)    5h12m
prometheus             prometheus-prometheus-node-exporter-zrwj5                         1/1     Running     0                3h16m
prometheus             prometheus-prometheus-pushgateway-7cfd5f66f4-r79cc                1/1     Running     1 (24h ago)      28h
prometheus             prometheus-server-7667d77498-5smqr                                2/2     Running     3 (24h ago)      28h
prometheus             prometheus-speedtest-exporter-7db5b7f6d5-59lxq                    1/1     Running     1 (24h ago)      5d13h
velero                 node-agent-6bn5g                                                  1/1     Running     1 (24h ago)      3d4h
velero                 node-agent-qs6sh                                                  1/1     Running     0                57m
velero                 node-agent-wk94j                                                  1/1     Running     2 (24h ago)      3d4h
velero                 velero-656d65767f-495t6                                           1/1     Running     0                144m
```
* `kubectl get services`:
```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   6d21h
```
* `kubectl get sc`:
```
NAME                       PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-cstore (default)   cstor.csi.openebs.io   Delete          Immediate              true                   3d5h
openebs-device             openebs.io/local       Delete          WaitForFirstConsumer   false                  5d6h
openebs-hostpath           openebs.io/local       Delete          WaitForFirstConsumer   false                  5d6h
```
* `kubectl get pv`:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                          STORAGECLASS     REASON   AGE
pvc-6bc3952d-5d34-45b8-94e3-50df769a96dc   10Gi       RWO            Retain           Bound    prometheus/prometheus                          openebs-cstore            3d6h
pvc-a3f50650-1d1d-4d2f-9062-49eea74f3c4b   2Gi        RWO            Delete           Bound    prometheus/storage-prometheus-alertmanager-0   openebs-cstore            4d22h
pvc-b73af6dc-11f9-407f-8a49-b479869efcc0   10Gi       RWO            Retain           Bound    grafana/grafana                                openebs-cstore            3d2h
pvc-bb0dc064-ce53-48e3-8788-7a5a7aae9655   10Gi       RWO            Retain           Bound    portainer/portainer                            openebs-cstore            3d6h
```
* `kubectl get pvc`:
```
NAMESPACE    NAME                                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
grafana      grafana                             Bound    pvc-b73af6dc-11f9-407f-8a49-b479869efcc0   10Gi       RWO            openebs-cstore   3d2h
portainer    portainer                           Bound    pvc-bb0dc064-ce53-48e3-8788-7a5a7aae9655   10Gi       RWO            openebs-cstore   3d6h
prometheus   prometheus                          Bound    pvc-6bc3952d-5d34-45b8-94e3-50df769a96dc   10Gi       RWO            openebs-cstore   3d6h
prometheus   storage-prometheus-alertmanager-0   Bound    pvc-a3f50650-1d1d-4d2f-9062-49eea74f3c4b   2Gi        RWO            openebs-cstore   4d22h
```
* OS (from `/etc/os-release`):
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
* Kernel (from `uname -a`):
```
Linux k8s-master-1 5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 14:02:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
* Install tools:
```
kubeadm version: &version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:20:04Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
kubectl version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
helm version: version.BuildInfo{Version:"v3.11.3", GitCommit:"66a969e7cc08af2377d055f4e6283c33ee84be33", GitTreeState:"clean", GoVersion:"go1.20.3"}
Installed from Helm chart openebs/openebs 3.5.0 from https://openebs.github.io/charts
```
* Others:

**Comment by pieveee** [comment]
I have the same problem and unfortunately OpenEBS documentation is not really helping.

I took a backup of the validatingwebhookconfiguration and deleted it afterwards:
```Bash
$ kubectl -n openebs get validatingwebhookconfigurations openebs-cstor-validation-webhook -o yaml > openebs-cstor-validation-webhook

$ kubectl -n openebs delete validatingwebhookconfigurations openebs-cstor-validation-webhook
```

This allows me to edit the cstorpoolcluster and remove the instance:
```Bash
$ kubectl -n openebs edit cstorpoolcluster
```

It's definitely not an elegant solution...

**Comment by pieveee** [comment]
Or even better: Modify the admission `failurePolicy` from `Fail` to `ignore`, make the changes and revert to `Fail`.

```Bash
$ kubectl edit validatingwebhookconfiguration openebs-cstor-validation-webhook
```

Read more here: https://openebs.io/docs/main/troubleshooting/cstor#pools-volume-offline
